services:
    app:
      env_file: "./src/.env"
      container_name: app
      build:
        context: .
        dockerfile: .docker/Dockerfile
        args:
          - VITE_ENABLED=${VITE_ENABLED}
          - XDEBUG_ENABLED=${XDEBUG_ENABLED}
          - UID=1000
          - GID=1000
          - APP_ENV=${APP_ENV}
      environment:
          - VITE_ENABLED=${VITE_ENABLED}
          - XDEBUG_ENABLED=${XDEBUG_ENABLED}
          - APP_ENV=${APP_ENV}
      restart: unless-stopped
      volumes:
        - ./src:/var/www/html
      ports:
        - 443:443
        - 80:80
        - 5173:5173
      depends_on:
        - db

    db:
      container_name: db
      image: mysql:8
      restart: unless-stopped
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306
      environment:
        - MYSQL_DATABASE=bill2
        - MYSQL_USER=bill2
        - MYSQL_PASSWORD=bill2
        - MYSQL_ROOT_PASSWORD=bill2
    mailpit:
      image: axllent/mailpit
      container_name: mailpit
      restart: unless-stopped
      volumes:
        - ./mail:/data
      ports:
        - 8025:8025
        - 1025:1025
      environment:
        MP_MAX_MESSAGES: 5000
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
