#!/usr/bin/with-contenv sh

# Enable opcache for production
if [ "$APP_ENV" == "production" ]; then
  echo "Enabling PHP-FPM's opcache for production";
else
  echo "PHP-FPM's opcache is NOT enabled";
fi


su www-data -s /bin/sh


cat <<EOL
┌─────────────────────┐
│┏━┓╻ ╻┏━┓   ┏━╸┏━┓┏┳┓│
│┣━┛┣━┫┣━┛╺━╸┣╸ ┣━┛┃┃┃│
│╹  ╹ ╹╹     ╹  ╹  ╹ ╹│
└─────────────────────┘
EOL

exec /usr/local/sbin/php-fpm --nodaemonize

