#!/usr/bin/with-contenv sh

# Enable opcache for production
if [ "$APP_ENV" == "production" ]; then
  echo "PRODUCTION"
else
  echo "DEV"
fi

su www-data -s /bin/sh

cat <<EOL
┌─────────────────────┐
│┏━┓╻ ╻┏━┓   ┏━╸┏━┓┏┳┓│
│┣━┛┣━┫┣━┛╺━╸┣╸ ┣━┛┃┃┃│
│╹  ╹ ╹╹     ╹  ╹  ╹ ╹│
└─────────────────────┘
EOL

exec /usr/local/sbin/php-fpm --nodaemonize