#!/usr/bin/with-contenv sh

# Enable queue for production
#su www-data -s /bin/sh

cat <<EOF
┌───────────────┐
│┏━┓╻ ╻┏━╸╻ ╻┏━╸│
│┃┓┃┃ ┃┣╸ ┃ ┃┣╸ │
│┗┻┛┗━┛┗━╸┗━┛┗━╸│
└───────────────┘
EOF


sleep 5
cd /var/www/html
exec s6-setuidgid www-data php artisan queue:work --tries=3
