#!/usr/bin/with-contenv sh

# Enable queue for production
su www-data -s /bin/sh

cat <<EOF
 ██████╗ ██╗   ██╗███████╗██╗   ██╗███████╗
██╔═══██╗██║   ██║██╔════╝██║   ██║██╔════╝
██║   ██║██║   ██║█████╗  ██║   ██║█████╗  
██║▄▄ ██║██║   ██║██╔══╝  ██║   ██║██╔══╝  
╚██████╔╝╚██████╔╝███████╗╚██████╔╝███████╗
 ╚══▀▀═╝  ╚═════╝ ╚══════╝ ╚═════╝ ╚══════╝
EOF


sleep 5
exec php /var/www/html/artisan queue:work --tries=3
